version: 2
jobs:
  build:
    working_directory: /go/src/github.com/yfuruyama/stackdriver-request-context-log
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go mod download
      - run: go vet ./...
      - run: go test -v ./...
