name: linter

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  golangci-lint:
    name: runner / golangci-lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: "--config=.github/.golangci.yml --timeout=10m"
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
